[phases]
[phases.build]
commands = [
    "cd aplicacao/aplicacao && mvn clean package",
    "cd aplicacao/frontend/app && npm install && npm run build"
]

[phases.start]
commands = [
    "cd aplicacao/aplicacao/target && java -jar aplicacao-0.0.1-SNAPSHOT.jar"
]