[phases]
build = [
    "cd aplicacao/aplicacao && .\\mvnw.cmd clean package",
    "cd aplicacao/frontend/app && npm install && npm run build"
]

start = [
    "cd aplicacao/aplicacao/target && java -jar aplicacao-0.0.1-SNAPSHOT.jar",
    "cd aplicacao/frontend/app/dist && npx serve -s ."
]