[phases]
[phases.build]
commands = [
    "cd aplicacao/aplicacao && mvn clean package",
    "cd aplicacao/frontend/app && npm install && npm run build"
]

[phases.start]
commands = [
    "cd aplicacao/aplicacao && java -jar target/*.jar"
]